/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bank_oop;

import perbankan.*;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class antrian extends javax.swing.JFrame {
    Bank bank;
    Queue bolang = new LinkedList();
    /** Creates new form antrian */
    public antrian(Bank bank) {
        initComponents();
        this.bank = bank;
        bt_move.setEnabled(false);
        bt_move1.setVisible(false);
    }
    void input() {
        int i = 0;
        for(int j=1; j<11; j++){
            i =j;
            bolang.add(i);
            ta1.append(i + "\n");
        }
    }

    void move(){
        if(bolang.peek()==null){
            JOptionPane.showMessageDialog(rootPane, "Queue kosong");
            ta1.setText("");
            bt_input.setEnabled(true);
            bt_move.setEnabled(false);
            bt_move1.setEnabled(false);
       }else{
            ta2.append(bolang.peek() + "\n");
            bolang.poll();
            ta1.setText(bolang + "");
            bt_input.setEnabled(false);
        }      
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_input = new javax.swing.JButton();
        ta1 = new javax.swing.JTextArea();
        bt_move = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ta2 = new javax.swing.JTextArea();
        bt_move1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_input.setText("Tambah Antrian");
        bt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inputActionPerformed(evt);
            }
        });

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ta1.setRows(5);

        bt_move.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_move.setText("Layani");
        bt_move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_moveActionPerformed(evt);
            }
        });

        bt_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_exit.setText("Exit");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ANTRIAN");

        ta2.setEditable(false);
        ta2.setColumns(20);
        ta2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ta2.setRows(5);
        ta2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bt_move1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_move1.setText("Selesai");
        bt_move1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_move1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ta1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bt_move, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bt_move1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ta2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_input)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(bt_input)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ta2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(ta1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_move)
                    .addComponent(bt_move1))
                .addGap(28, 28, 28)
                .addComponent(bt_exit)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inputActionPerformed
        // TODO add your handling code here:
        input();
        ta2.setText("");
        bt_move.setEnabled(true);
        bt_move1.setVisible(true);
        bt_move1.setEnabled(false);
    }//GEN-LAST:event_bt_inputActionPerformed

    private void bt_moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_moveActionPerformed
        move();
        Teller teller = new Teller(bank);
        teller.show();
        bt_move.setEnabled(false);
        bt_move1.setEnabled(true);
    }//GEN-LAST:event_bt_moveActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_move1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_move1ActionPerformed
        bt_move.setEnabled(true);
        bt_move1.setEnabled(false);
    }//GEN-LAST:event_bt_move1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_input;
    private javax.swing.JButton bt_move;
    private javax.swing.JButton bt_move1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextArea ta2;
    // End of variables declaration//GEN-END:variables

}
